[build]
  # Command to build the Quarto site
  command = "quarto render"
  # Folder to publish to Netlify
  publish = "_site"
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF docker/"

[[plugins]]
package = "@quarto/netlify-plugin-quarto"